// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJSz8brIeW_tPUMWjyxn6H5Hl3bIidFoA',
    appId: '1:103128459937:web:687e2295a3684cc6ce9ee0',
    messagingSenderId: '103128459937',
    projectId: 'movieapp-b297b',
    authDomain: 'movieapp-b297b.firebaseapp.com',
    storageBucket: 'movieapp-b297b.appspot.com',
    measurementId: 'G-6FPD1XWT53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhOu_wFmCmb9oTyJ7qD0G1rzdorOFCWLY',
    appId: '1:103128459937:android:e83c96829a8a9ee5ce9ee0',
    messagingSenderId: '103128459937',
    projectId: 'movieapp-b297b',
    storageBucket: 'movieapp-b297b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCWI0mKyayfedXTJeAa9apu0Eetw97bw',
    appId: '1:103128459937:ios:3203690332b85042ce9ee0',
    messagingSenderId: '103128459937',
    projectId: 'movieapp-b297b',
    storageBucket: 'movieapp-b297b.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtCWI0mKyayfedXTJeAa9apu0Eetw97bw',
    appId: '1:103128459937:ios:3203690332b85042ce9ee0',
    messagingSenderId: '103128459937',
    projectId: 'movieapp-b297b',
    storageBucket: 'movieapp-b297b.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJSz8brIeW_tPUMWjyxn6H5Hl3bIidFoA',
    appId: '1:103128459937:web:d27e910af6b4a359ce9ee0',
    messagingSenderId: '103128459937',
    projectId: 'movieapp-b297b',
    authDomain: 'movieapp-b297b.firebaseapp.com',
    storageBucket: 'movieapp-b297b.appspot.com',
    measurementId: 'G-1P0RTRV2B0',
  );
}
